### ISSUE TITLE
wrong reuslt

### ISSUE THREAD

**Issue by jinfagang** [TimoBolkart/BFM_to_FLAME#14] opened 2022-03-06 07:49 UTC
<img width="692" alt="image" src="https://user-images.githubusercontent.com/21303438/156914122-3a83ad24-62de-4434-81dc-1a742b19bffd.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/21303438/156914130-f87809fc-d531-4ea6-b52a-115cdfa86961.png">

the example even not right...

**Comment by jinfagang** [comment] 2022-03-10 13:24
@TimoBolkart Hi, the first one the default obj file (although it looks like already weird). I removed the mesh lib using inside since it have a lot of dependencies and some of them are out-of-dated. 

Anyway, I found the optimization takes about 10 min to get a wrong result, so I give it up, it can not fit a textured obj from bfm to flame right?

**Comment by TimoBolkart** [comment] 2022-03-10 13:27
What is the default obj file? It looks weird because the rendering looks from the back at it I guess, so you see the face from the inside. Can you share just that one obj file with me?

**Comment by jinfagang** [comment] 2022-03-11 01:47
https://github.com/TimoBolkart/BFM_to_FLAME/blob/main/data/134212_1.obj

**Comment by TimoBolkart** [comment] 2022-03-16 10:17
Unfortunately, I cannot reproduce this error. What changes do you have in the code? Are you sure that the file is loaded properly and that vertices are not permuted after loading (Trimesh for instance by default permutes the vertices when loading a mesh)

Running mesh_convert.py for this file gives me following result 
![134212_1__FLAME_fit](https://user-images.githubusercontent.com/26549953/158567434-01d8ae38-9aa0-43b5-8a3c-8671838c3487.png)

And this is the input BFM file rendered with the same view
![134212_1](https://user-images.githubusercontent.com/26549953/158567425-b8da08f7-0754-4639-a30b-d045e14054c2.png)

**Comment by jinfagang** [comment] 2022-03-16 10:28
@TimoBolkart thanks, the first weird pic is directly is via macOS preview application. It looks not quite normal.

**Comment by TimoBolkart** [comment] 2022-03-16 10:52
You are looking from the back onto the face, just rotate it, then it will look ok.

**Comment by TimoBolkart** [comment] 2022-08-10 15:38
Closed as there was no further response

**Closed by TimoBolkart** 2022-08-10 15:38 UTC
